# Generated by Django 3.1.4 on 2021-06-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210606_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
