# Generated by Django 3.1 on 2021-06-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210606_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplans',
            options={'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name_plural': 'User Subscription'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='date',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='quantity_accesserios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='quantity_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='freezedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='freezestatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscriptionplans'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
