# Generated by Django 3.1 on 2021-06-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210608_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription_plan',
            new_name='plan',
        ),
    ]
