# Generated by Django 3.1 on 2021-06-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
