# Generated by Django 3.1.4 on 2021-05-05 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_mrp', models.IntegerField(blank=True)),
                ('selling_mrp', models.IntegerField(blank=True)),
                ('rental_mrp', models.IntegerField(blank=True)),
                ('security_deposit', models.IntegerField(default=1000)),
                ('discount_percent', models.IntegerField(blank=True)),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('neck_design', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('designer', models.CharField(blank=True, max_length=60)),
                ('small_size_available', models.BooleanField()),
                ('small_size_length', models.IntegerField()),
                ('small_size_bust', models.IntegerField()),
                ('small_size_waist', models.IntegerField()),
                ('medium_size_available', models.BooleanField()),
                ('medium_size', models.BooleanField()),
                ('medium_size_length', models.IntegerField()),
                ('medium_size_bust', models.IntegerField()),
                ('medium_size_waist', models.IntegerField()),
                ('large_size_available', models.BooleanField()),
                ('large_size_length', models.IntegerField()),
                ('large_size_bust', models.IntegerField()),
                ('large_size_waist', models.IntegerField()),
                ('extra_large_size_available', models.BooleanField()),
                ('extra_large_size_length', models.IntegerField()),
                ('extra_large_size_bust', models.IntegerField()),
                ('extra_large_size_waist', models.IntegerField()),
                ('sleeves', models.BooleanField()),
                ('in_stock', models.BooleanField()),
                ('is_available_for_rent', models.BooleanField()),
                ('is_available_for_sale', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('brand', models.ManyToManyField(to='ecommerce.Brand')),
                ('category', models.ManyToManyField(to='ecommerce.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5)),
                ('promocode', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
