# Generated by Django 3.1.4 on 2021-05-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20210507_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bag',
            name='promocode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
