# Generated by Django 3.1.4 on 2021-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20210509_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Brand'),
        ),
    ]
