# Generated by Django 3.1.4 on 2021-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_deliverypincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypincode',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
