# Generated by Django 3.1.4 on 2021-05-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_deliverypincode_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='promocode',
        ),
    ]
