# Generated by Django 3.1.4 on 2021-05-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20210510_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Add/View Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Add/View Product Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Add/View Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='only_for_subscribed_user',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_mrp',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DealsOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_selling_mrp', models.IntegerField()),
                ('today_rental_mrp', models.IntegerField()),
                ('today_discount_percent', models.IntegerField(blank=True)),
                ('only_for_subscribed_user', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product')),
            ],
        ),
    ]
