# Generated by Django 3.1.4 on 2021-05-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0011_auto_20210510_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='Ecommerce/Clothes')),
                ('product_mrp', models.IntegerField()),
                ('selling_mrp', models.IntegerField()),
                ('rental_mrp', models.IntegerField()),
                ('security_deposit', models.IntegerField(default=1000)),
                ('discount_percent', models.IntegerField(blank=True)),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('neck_design', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('designer', models.CharField(blank=True, max_length=60)),
                ('sleeves', models.BooleanField()),
                ('in_stock', models.BooleanField()),
                ('is_available_for_rent', models.BooleanField()),
                ('is_available_for_sale', models.BooleanField()),
                ('only_for_subscribed_user', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('brand', models.ManyToManyField(to='ecommerce.Brand')),
                ('category', models.ManyToManyField(to='ecommerce.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Add/View Accessories',
            },
        ),
    ]
