# Generated by Django 3.1.4 on 2021-05-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20210511_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('Deals Of The Day', 'Deals Of The Day'), ('Festive Special', 'Festive Special'), ('Summer Collection', 'Summer Collection'), ('Winter Collection', 'Winter Collection')], max_length=20)),
                ('today_selling_mrp', models.IntegerField()),
                ('today_rental_mrp', models.IntegerField()),
                ('today_discount_percent', models.IntegerField(blank=True)),
                ('only_for_subscribed_user', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product')),
            ],
        ),
        migrations.DeleteModel(
            name='DealsOfTheDay',
        ),
    ]
