# Generated by Django 3.1.4 on 2021-05-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210511_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_mrp',
            new_name='rental_selling_mrp',
        ),
    ]
