# Generated by Django 3.1.4 on 2021-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_auto_20210518_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Brand'),
        ),
    ]
