# Generated by Django 3.1.4 on 2021-05-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20210518_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='product_image1',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image2',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image3',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image4',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image5',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image5',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image6',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Review'),
        ),
    ]
