# Generated by Django 3.1.4 on 2021-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20210518_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Brand'),
        ),
    ]
