# Generated by Django 3.1.4 on 2021-05-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20210518_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_rental_mrp', models.IntegerField()),
                ('today_discount_percent', models.IntegerField(blank=True)),
                ('only_for_subscribed_user', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product')),
            ],
        ),
    ]
