# Generated by Django 3.1.4 on 2021-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_dealsofday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='today_selling_mrp',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='today_discount_percent',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Deals Of The Day', 'Deals Of The Day'), ('Festive Special', 'Festive Special'), ('Summer Collection', 'Summer Collection'), ('Winter Collection', 'Winter Collection'), ('As Seen Your Favourite', 'As Seen Your Favourite')], max_length=25),
        ),
        migrations.DeleteModel(
            name='DealsOfDay',
        ),
    ]
