# Generated by Django 3.1.4 on 2021-05-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_auto_20210520_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='discount_percent',
        ),
    ]
