# Generated by Django 3.1.4 on 2021-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_remove_accessories_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rental_selling_mrp',
        ),
        migrations.AddField(
            model_name='accessories',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
