# Generated by Django 3.1.4 on 2021-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20210520_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.FloatField(),
        ),
    ]
