# Generated by Django 3.1.4 on 2021-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20210520_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Brand'),
        ),
    ]
