# Generated by Django 3.1.4 on 2021-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_auto_20210520_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='selling_mrp',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='sleeves',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='user',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image1',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Accessories'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image2',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Accessories'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image3',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Accessories'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image4',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Accessories'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_image5',
            field=models.FileField(blank=True, null=True, upload_to='Ecommerce/Accessories'),
        ),
    ]
