# Generated by Django 3.1.4 on 2021-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_auto_20210520_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5, null=True),
        ),
    ]
