# Generated by Django 3.1 on 2021-06-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210608_1523'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0031_auto_20210520_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=34)),
                ('phone', models.CharField(max_length=13)),
                ('country', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('mode', models.CharField(default='', max_length=200)),
                ('received_by', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('MOP', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='bag',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='accessories',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessories',
            name='subscription_plan',
            field=models.ManyToManyField(blank=True, null=True, to='core.SubscriptionPlans'),
        ),
        migrations.AddField(
            model_name='bag',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.accessories'),
        ),
        migrations.AddField(
            model_name='bag',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='order_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bag',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bag',
            name='orderid',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AddField(
            model_name='bag',
            name='payment_id',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='promocode',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bag',
            name='reorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bag',
            name='single_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='total_bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bag',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.accessories'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_plan',
            field=models.ManyToManyField(blank=True, null=True, to='core.SubscriptionPlans'),
        ),
        migrations.AddField(
            model_name='review',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.accessories'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.accessories'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, choices=[('Debit/Credit Card', 'Debit/Credit Card'), ('E-Wallet', 'E-Wallet')], default=' ', max_length=50)),
                ('amount_paid', models.IntegerField(default=0)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='user/payment/invoice')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Payment',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('packed', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('Tracking_Details', models.TextField(default='', null=True)),
                ('Order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedBag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.bag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.bag'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
