# Generated by Django 3.1 on 2021-06-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_auto_20210608_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='total_bill',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='review',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='accessories',
        ),
        migrations.AddField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleeves',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.AddField(
            model_name='items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.items'),
        ),
    ]
