# Generated by Django 3.1 on 2021-06-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_auto_20210610_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Add Products'},
        ),
    ]
