# Generated by Django 3.1 on 2021-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_auto_20210610_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='order',
            field=models.ManyToManyField(to='ecommerce.Order'),
        ),
    ]
