# Generated by Django 3.1 on 2021-06-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_userpayment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='size',
        ),
    ]
