# Generated by Django 3.1 on 2021-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.FileField(blank=True, default=1, upload_to='Ecommerce/Clothes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.FileField(blank=True, default=1, upload_to='Ecommerce/Clothes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.FileField(blank=True, default=2, upload_to='Ecommerce/Clothes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.FileField(blank=True, upload_to='Ecommerce/Clothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image5',
            field=models.FileField(blank=True, upload_to='Ecommerce/Clothes'),
        ),
    ]
