# Generated by Django 3.1 on 2021-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20210611_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_large_size_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_large_size_bust',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_large_size_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_large_size_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_large_size_waist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='large_size_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='large_size_bust',
        ),
        migrations.RemoveField(
            model_name='product',
            name='large_size_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='large_size_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='large_size_waist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='medium_size_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='medium_size_bust',
        ),
        migrations.RemoveField(
            model_name='product',
            name='medium_size_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='medium_size_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='medium_size_waist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_size_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_size_bust',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_size_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_size_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_size_waist',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=255, null=True),
        ),
    ]
