# Generated by Django 3.1 on 2021-06-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_auto_20210630_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='add_date',
        ),
    ]
