# Generated by Django 3.1 on 2021-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
