# Generated by Django 3.1 on 2021-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_bag_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='today_product_mrp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
