# Generated by Django 3.1 on 2021-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_offer_today_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bag',
            name='rent',
            field=models.BooleanField(default=False),
        ),
    ]
