# Generated by Django 3.1 on 2021-07-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_auto_20210703_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='MOP',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reorder',
        ),
        migrations.AddField(
            model_name='bag',
            name='orderid',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AddField(
            model_name='bag',
            name='payment_id',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.bag'),
        ),
    ]
